name = "jail-visit-api-enhanced"
main = "worker-enhanced.js"
compatibility_date = "2024-01-01"

# KV Namespaces
[[kv_namespaces]]
binding = "USERS"
id = "cf359fa838de461b90d015512bc67051"

[[kv_namespaces]]
binding = "VISITS"
id = "962bffb03dcc4491b1c0ef9c76141c7a"

[[kv_namespaces]]
binding = "SETTINGS"
id = "9733724064cf452ba816404fd71981e1"

# New KV namespaces for enhanced features (you'll need to create these)
[[kv_namespaces]]
binding = "PENDING_USERS"
id = "YOUR_PENDING_USERS_KV_ID"

[[kv_namespaces]]
binding = "LOGIN_PINS"
id = "YOUR_LOGIN_PINS_KV_ID"

[[kv_namespaces]]
binding = "RESET_CODES"
id = "YOUR_RESET_CODES_KV_ID"

# Environment variables
[vars]
JWT_SECRET = "karpay-jail-visit-secure-jwt-2024-production-key-7x9z"

# Twilio Configuration (for SMS)
# Get these from https://console.twilio.com/
TWILIO_ACCOUNT_SID = "YOUR_TWILIO_ACCOUNT_SID"
TWILIO_AUTH_TOKEN = "YOUR_TWILIO_AUTH_TOKEN"
TWILIO_PHONE_NUMBER = "YOUR_TWILIO_PHONE_NUMBER"

# Mailgun Configuration (for Email)
# Get these from https://app.mailgun.com/
MAILGUN_API_KEY = "YOUR_MAILGUN_API_KEY"
MAILGUN_DOMAIN = "YOUR_MAILGUN_DOMAIN"