name = "jail-visit-api-enhanced"
main = "worker-email-only.js"
compatibility_date = "2024-01-01"

# Existing KV Namespaces
[[kv_namespaces]]
binding = "USERS"
id = "cf359fa838de461b90d015512bc67051"

[[kv_namespaces]]
binding = "VISITS"
id = "962bffb03dcc4491b1c0ef9c76141c7a"

[[kv_namespaces]]
binding = "SETTINGS"
id = "9733724064cf452ba816404fd71981e1"

# New KV namespaces for enhanced features
[[kv_namespaces]]
binding = "PENDING_USERS"
id = "01afca8caba04fde817b7b578bf82607"

[[kv_namespaces]]
binding = "LOGIN_PINS"
id = "3349ff23eff24afbab1f7d786ea94b17"

[[kv_namespaces]]
binding = "RESET_CODES"
id = "34fc339022bc4155b11e2d48aeaea13b"

# Environment variables
[vars]
JWT_SECRET = "karpay-jail-visit-secure-jwt-2024-production-key-7x9z"

# SendGrid Configuration
# Get API key from https://app.sendgrid.com/settings/api_keys
SENDGRID_API_KEY = "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"

# Email address to send from (must be verified in SendGrid)
FROM_EMAIL = "david@karpaylegal.com"