name = "cleanup-jail-visit"
main = "cleanup-script.js"
compatibility_date = "2024-01-01"

# Same KV Namespaces as your main worker
[[kv_namespaces]]
binding = "USERS"
id = "cf359fa838de461b90d015512bc67051"

[[kv_namespaces]]
binding = "PENDING_USERS"
id = "01afca8caba04fde817b7b578bf82607"

[[kv_namespaces]]
binding = "LOGIN_PINS"
id = "3349ff23eff24afbab1f7d786ea94b17"

[[kv_namespaces]]
binding = "RESET_CODES"
id = "34fc339022bc4155b11e2d48aeaea13b"
