name = "jail-visit-api"
main = "worker.js"
compatibility_date = "2024-01-01"

# KV Namespaces
# You'll need to create these in Cloudflare dashboard and update the IDs
[[kv_namespaces]]
binding = "USERS"
id = "cf359fa838de461b90d015512bc67051"

[[kv_namespaces]]
binding = "VISITS"
id = "962bffb03dcc4491b1c0ef9c76141c7a"

[[kv_namespaces]]
binding = "SETTINGS"
id = "9733724064cf452ba816404fd71981e1"

# Environment variables
[vars]
JWT_SECRET = "karpay-jail-visit-secure-jwt-2024-production-key-7x9z"